# This workflow will validate the Packer AMI templates created using the Hashicorp Configuration Language (HCL2)
name: Packer AMI template validation

on:
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Build artifacts
        run: |
          zip -r webapp.zip ./
          pwd ./webapp

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Packer init
        id: init
        run: 'packer init ami.pkr.hcl'

      - name: Validate packer template
        id: validate
        run: 'packer validate -evaluate-datasources ami.pkr.hcl'
