# This workflow will validate the Packer AMI templates created using the Hashicorp Configuration Language (HCL2)
name: Packer AMI template validation

on:
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: Build artifacts
        run: |
          zip -r webapp.zip ./
          pwd ./webapp

      - name: Packer variables
        run: |
          touch ami.pkrvars.hcl
          echo ami_prefix=${{ secrets.AMI_PREFIX }} >> ami.pkrvars.hcl
          echo OS=$${{ secrets.OS }} >> ami.pkrvars.hcl
          echo ubuntu_version=${{ secrets.VERSION }} >> ami.pkrvars.hcl
          echo ssh_username=${{ secrets.SSH }} >> ami.pkrvars.hcl
          echo subnet_id=${{ secrets.SUBNET_ID }} >> ami.pkrvars.hcl
          echo dev_id=${{ secrets.DEV_ID }} >> ami.pkrvars.hcl
          echo prod_id=${{ secrets.PROD_ID }} >> ami.pkrvars.hcl
          echo source_ami=${{ secrets.SOURCE_AMI }} >> ami.pkrvars.hcl
          echo aws_region=${{ env.AWS_REGION }} >> ami.pkrvars.hcl
          echo instance_type=${{ secrets.INSTANCE_TYPE}} >> ami.pkrvars.hcl

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Packer format
        id: fmt
        run: 'packer fmt .'

      - name: Packer init
        id: init
        run: 'packer init ami.pkr.hcl'

      - name: Validate packer template
        id: validate
        run: 'packer validate -evaluate-datasources --var-file=ami.pkrvars.hcl ami.pkr.hcl'
