name: Instance Refresh

env:
  ARTIFACT_NAME: webapp
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ENVIRONMENT: test
  HOSTNAME: ${{ secrets.HOSTNAME }}
  PORT: ${{ secrets.PORT }}
  DATABASE: ${{ secrets.DATABASE }}
  DBUSER: ${{ secrets.DBUSER }}
  DBPASSWORD: ${{ secrets.DBPASSWORD }}
  AWS_PROD_ACCESS_KEY: ${{ secrets.AWS_PROD_ACCESS_KEY }}
  AWS_PROD_SECRET_KEY: ${{ secrets.AWS_PROD_SECRET_KEY }}
  AWS_DEV_ACCESS_KEY: ${{ secrets.AWS_DEV_ACCESS_KEY }}
  AWS_DEV_SECRET_KEY: ${{ secrets.AWS_DEV_SECRET_KEY }}
  LAUNCH_CONFIG: ${{ secrets.LAUNCH_CONFIG }}
  ASG_NAME: ${{ secrets.ASG_NAME }}
on:
  push:
    branches: [master]
jobs:
  # Check basic tests
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: 'Create .env file'
        run: |
          touch .env
          echo ENVIRONMENT=${{ env.ENVIRONMENT }} >> .env
          echo HOSTNAME=${{ env.HOSTNAME }} >> .env
          echo PORT=${{ env.PORT }} >> .env
          echo DATABASE=${{ env.DATABASE }} >> .env
          echo DBUSER=${{ env.DBUSER }} >> .env
          echo DBPASSWORD=${{ env.DBPASSWORD }} >> .env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
  # Packer init, validate and build
  packer:
    needs: tests
    runs-on: ubuntu-latest
    name: Build AWS Custom AMI with REST API app artifacts
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Build artifacts
        run: |
          touch .env
          echo ENVIRONMENT=${{ env.ENVIRONMENT }} >> .env
          echo HOSTNAME=${{ env.HOSTNAME }} >> .env
          echo PORT=${{ env.PORT }} >> .env
          echo DATABASE=${{ env.DATABASE }} >> .env
          echo DBUSER=${{ env.DBUSER }} >> .env
          echo DBPASSWORD=${{ env.DBPASSWORD }} >> .env
          zip -r webapp.zip ./
          pwd ./webapp

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ami.pkr.hcl

      - name: Validate packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate -evaluate-datasources
          target: ami.pkr.hcl

      - name: Packer build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: '-color=false -on-error=abort'
          target: ami.pkr.hcl
        env:
          PACKER_LOG: 1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_PROD_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Instance Refresh automation
        run: |
          sudo apt-get install jq
          ASG_NAME=${{ env.ASG_NAME }}
          LAUNCH_CONFIG=${{ env.LAUNCH_CONFIG }}
          IMAGE=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
          IMAGE_ID=$(jq -n \
            --arg img "$IMAGE" \
            '{"ImageId": $img}')
          aws ec2 create-launch-template-version \
            --launch-template-name "$LAUNCH_CONFIG" \
            --version-description updateAMI --source-version 1 \
            --launch-template-data="$IMAGE_ID"
          TEMPLATE_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name="$LAUNCH_CONFIG" \
            --filters="Name=is-default-version,Values=false" \
            --query 'sort_by(LaunchTemplateVersions, &CreateTime)[-1].[VersionNumber]' --output text)
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
            --launch-template LaunchTemplateName="$LAUNCH_CONFIG",Version=$TEMPLATE_VERSION
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name $ASG_NAME --strategy Rolling
          printf "Instance refresh in progress"
          while true;
          do
            instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME \
              --query "InstanceRefreshes[0].Status" --output text)
            if [ "$instance_refresh_status" = "Successful" ]; then
              printf "\nInstance refresh successful!"
              break
            fi
            if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
              printf "\nInstance refresh failed!"
              exit 1
            fi
            echo -ne "."
            sleep 10
          done
