# This workflow will validate the Packer AMI templates created using the Hashicorp Configuration Language (HCL2)
name: Packer AMI template validation

on:
  # for public repos
  pull_request_target:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate packer template for the custom AMI
    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Build artifacts
        run: |
          zip -r webapp.zip ./
          pwd ./webapp

      - name: Packer init
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: ami.pkr.hcl

      - name: Validate packer template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate -evaluate-datasources
          target: ami.pkr.hcl