# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test Suite

env:
  ENVIRONMENT: test
  HOSTNAME: ${{ secrets.HOSTNAME }}
  PORT: ${{ secrets.PORT }}
  DATABASE: ${{ secrets.DATABASE }}
  DBUSER: ${{ secrets.DBUSER }}
  DBPASSWORD: ${{ secrets.DBPASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    name: Run unit tests
    steps:
      - uses: actions/checkout@v2
      - name: 'Create .env file'
        run: |
          touch .env
          echo ENVIRONMENT=${{ env.ENVIRONMENT }} >> .env
          echo HOSTNAME=${{ env.HOSTNAME }} >> .env
          echo PORT=${{ env.PORT }} >> .env
          echo DATABASE=${{ env.DATABASE }} >> .env
          echo DBUSER=${{ env.DBUSER }} >> .env
          echo DBPASSWORD=${{ env.DBPASSWORD }} >> .env
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
